environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
  ALINODE_SECRET:
    secure: UamTdw8+EnNWPGtCRoeFxq1hGiKNB93g3wRZDAqmjo6HD0tXg7csiNefj+Jh1lNt
  ALINODE_APPID:
    secure: uiW61hX3RFWXm2VVpCIOEA==

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i npminstall && node_modules\.bin\npminstall

test_script:
  - npm run ci

build: off
